### ISSUE TITLE
Question: Obtain device hardware and firmware versions in DFU mode

### ISSUE THREAD

**Issue by Dario-GoldenSpear** [NordicSemiconductor/IOS-nRF-Toolbox#118] opened 2021-10-18 22:38 UTC
**DFU Bootloader version (please complete the following information):**
 - SDK version: 17.0.2
 - Bonding used: no
 - Library version: 4.10.4

**Device information (please complete the following information):**
 - Device: iPhone 7+
 - OS: 14.8
- Nordic Device: nRF 52 Dev. Kit.

**Your question**
we have an iOS app based on this project. We were able to:
-  flash the dev. kit using Segger and the sample SDK project:
`../nRF5_SDK/nRF5_SDK_17.0.2_d674dde/examples/dfu/secure_bootloader/pca10040_s132_ble/`
- enter DFU mode (button 4 + reset, no buttonless mode yet)
- perform OTA DFU from the iOS application using a custom .zip firmware package with our devkit code downloaded from a backend using the device's name.

Question:
We would like to obtain the device hardware and firmware revision to obtain the latest  .zip firmware package from the backend. 
Is it possible to do that in DFU mode (no buttonless) from the iOS application? and if so, how do we get that information?

ADDITIONAL NOTES:
I've tried exposing the required data by setting this:
`#define NRF_DFU_PROTOCOL_REDUCED 0`

in:
`.../nRF5_SDK_17.0.2_d674dde/examples/dfu/secure_bootloader/pca10040_s132_ble/config/sdk_config.h(1252`

which in turn enables a couple of methods (that afaik may be part of the solution to expose the required data):
`static void on_hw_version_request(nrf_dfu_request_t const * p_req, nrf_dfu_response_t * p_res)`
`static void on_fw_version_request(nrf_dfu_request_t const * p_req, nrf_dfu_response_t * p_res)`

in:
`...nRF5_SDK_17.0.2_d674dde/components/libraries/bootloader/dfu/nrf_dfu_req_handler.c(107)`

**Comment by philips77** [comment] 2021-10-19 05:09
Duplicate of https://github.com/NordicSemiconductor/IOS-DFU-Library/issues/462.

**Closed by philips77** 2021-10-19 05:09 UTC
