### ISSUE TITLE
IOS TOOLBOX DFU upload failure

### ISSUE THREAD

**Issue by ArthurHCL** [NordicSemiconductor/IOS-nRF-Toolbox#41] opened 2017-12-13 00:32 UTC
toolbox which version is newly on IOS,DFU can not work,I have found the reason...at upload start,toolbox does NOT write CCCD of DFU control point,so device think it is a failure,then RESET.
could you solve the problem of toolbox?

**Comment by mostafaberg** [comment] 2017-12-14 13:38
Hi Arthur, can you send us example firmware that reproduces this issue ? and perhaps the exact logs so we can know what the exact issue is ?

**Comment by Paluche** [comment] 2017-12-21 09:47
Hi @mostafaberg and @ArthurHCL I think I have the same problem, that could be seen also with the DFU on the nRF connect iOS application. The two applications can't activate the notifications on the Control Point characteristics. nRF Connect provides more informations on this matter:
![img_0003](https://user-images.githubusercontent.com/3624038/34249537-5bcc325a-e63a-11e7-9253-4c225683762a.PNG)

I haven't been able to test with earlier versions of iOS. But the code I run on the embedded part works fine when running the DFU on the nRF Android applications.

**Comment by philips77** [comment] 2017-12-21 20:35
Hi, I see there 2 issue: as far as I know, the current DFU doesn't support higher MTUs, but your support 185+3, is it a custom modified one?
Looks like your control point characteristic doesn't have the required Client Characteristic Configuration descriptor, or there is an issue with caching. Did you try if it works on Android in nRF Connect?

**Comment by ArthurHCL** [comment] 2017-12-22 02:09
@mostafaberg I have solved this problem: I mistakenly used the HEX file directly for the DFU without adding the INIT package ... Now that my DFU is working perfectly, thanks!

**Comment by Paluche** [comment] 2017-12-22 12:40
@philips77 Yes it is a custom DFU and yes it works fine with the nRF Connect Android application. 
The custom DFU is basically a copy paste from the SDK sources.

**Comment by mostafaberg** [comment] 2018-01-12 07:52
@ArthurHCL Glad to hear it works for you!
@Paluche Can you open up a new issue so we can support you there instead ? thanks, closing this for now as it's resolved

**Closed by mostafaberg** 2018-01-12 07:52 UTC
